#!/bin/bash
echo Setting profile for performance
tuned-adm profile throughput-performance
asusctl profile -P Performance

WAYLANDDRV_PRIMARY_MONITOR=DP-10 PROTON_ENABLE_WAYLAND=1 __NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only __GLX_VENDOR_LIBRARY_NAME=nvidia gamemoderun "$@"

echo Setting profile for quiet
tuned-adm profile balanced
asusctl profile -P LowPower
