# Notification Daemon
exec-once = dunst

exec-once = nm-applet

exec-once = blueman-applet

exec-once = rog-control-center

exec-once = systemctl --user start hyprpolkitagent

exec-once = hyprpaper

exec-once = waybar
