import = [
	"~/.config/alacritty/catppuccin-mocha.toml"
]


[window]
dimensions = { columns = 100, lines = 45 }
padding = { x = 10, y = 10 }
#decorations = "None"
opacity = 0.95

[font]
normal = { family = "FiraCode Nerd Font" }
size = 13

[mouse]
hide_when_typing = true

[hints]
enabled = [{ hyperlinks = true, action = "Copy" }]

